# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('NZ', 'New Zealand'), ('IN', 'International'), ('TH', 'Tech'), ('SP', 'Sports')], default='NZ', max_length=2),
        ),
    ]
